name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build PHP image
        run: |
          docker build -t php -f Dockerfile .
          docker tag php:latest ${{ secrets.ECR_REPOSITORY_PHP }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_PHP }}:latest

      - name: Build Nginx image
        run: |
          docker build -t nginx -f Dockerfile.nginx .
          docker tag nginx:latest ${{ secrets.ECR_REPOSITORY_NGINX }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_NGINX }}:latest